### ISSUE TITLE
Nice work on the site

### ISSUE THREAD

**Issue by stuaxo** [thstsa/spacetourism#19]
A shame your CTE is out of touch and doesn't know about modern tools (that have been around for a decade), perhaps more of a learning experience than it would have been if everything went normally !

**Comment by nxame** [comment]
@shiloholotu @nolanqyee @thstsa @Bean0-0 Clapping for all of you. 

I echo what @stuaxo said - this incident gives you much more teaching and experience. 

Your post blew it on HN. https://news.ycombinator.com/item?id=34906444 If you didn't know HN, it's a forum where more like-minded and much more healthy discussions happen - you guys should make it to your bookmark and visit, it's worthwhile.

**Comment by Bean0-0** [comment]
Thanks for the support!
