### ISSUE TITLE
New icon

### ISSUE THREAD

**Issue by Bean0-0** [thstsa/spacetourism#2]
![image](https://user-images.githubusercontent.com/72772737/212915583-7f5f9629-94dd-41b0-b0a5-53be10b34718.png)

**Comment by Bean0-0** [comment]
![attachment_110460333](https://user-images.githubusercontent.com/72772737/212915670-009c0429-c5ca-4982-bd60-a44e38e46fc7.jpg)

**Comment by thstsa** [comment]
Probably against the rules😕
